
      - name: Definir PATH_PREFIX
        run: |
          echo "PATH_PREFIX=/${GITHUB_REPOSITORY#*/}/" >> $GITHUB_ENV
      - name: Build produção
        run: npm run prod
      - name: Verificar symlinks em _site
        run: find ./_site -type l
      - name: Listar arquivos grandes em _site
        run: find ./_site -type f -size +100M
      - name: Upload artefato do site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Instalar GitHub CLI
        run: |
          sudo apt-get install gh
      - name: Criar issue de status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STATUS: ${{ job.status }}
          TODAY: ${{ github.event.head_commit.timestamp || github.event.pull_request.updated_at || github.event.workflow_dispatch.created_at || github.run_started_at }}
          KB_URL: ${{ steps.deployment.outputs.page_url }}
        run: |
          gh issue create \
            --repo "$GITHUB_REPOSITORY" \
            --title "${TODAY%%T*} - Deployment: ${STATUS^}" \
            --body "URL: $KB_URL"
